import 'package:peaceit/domain/levels/entities/cell_entity.dart';
import 'package:peaceit/domain/levels/entities/level_entity.dart';

class DefaultLevels {
  static const List<LevelEntity> levels = [
    // ------------------- CHAPTER 1 -------------------
    LevelEntity(id: 'c1n1', chapterId: '1', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c1n2', chapterId: '1', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(1, 3),
    ]),
    LevelEntity(id: 'c1n3', chapterId: '1', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(2, 3),
    ]),
    LevelEntity(id: 'c1n4', chapterId: '1', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c1n5', chapterId: '1', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 4),
    ]),
    LevelEntity(id: 'c1n6', chapterId: '1', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(2, 1),
      CellEntity(2, 3),
    ]),

    // ------------------- CHAPTER 2 -------------------

    LevelEntity(id: 'c2n1', chapterId: '2', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(1, 2),
      CellEntity(4, 2),
    ]),
    LevelEntity(id: 'c2n2', chapterId: '2', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(1, 4),
    ]),
    LevelEntity(id: 'c2n3', chapterId: '2', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(3, 3),
    ]),
    LevelEntity(id: 'c2n4', chapterId: '2', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 1),
      CellEntity(2, 4),
    ]),
    LevelEntity(id: 'c2n5', chapterId: '2', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(1, 2),
      CellEntity(1, 3),
    ]),
    LevelEntity(id: 'c2n6', chapterId: '2', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(3, 2),
    ]),
    LevelEntity(id: 'c2n7', chapterId: '2', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 1),
      CellEntity(2, 3),
    ]),
    LevelEntity(id: 'c2n8', chapterId: '2', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c2n9', chapterId: '2', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(1, 3),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c2n10', chapterId: '2', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(3, 1),
    ]),
    LevelEntity(id: 'c2n11', chapterId: '2', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c2n12', chapterId: '2', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(1, 2),
      CellEntity(2, 1),
    ]),

    // ------------------- CHAPTER 3 -------------------

    LevelEntity(id: 'c3n1', chapterId: '3', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c3n2', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(3, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c3n3', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c3n4', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(4, 1),
      CellEntity(4, 4),
    ]),
    LevelEntity(id: 'c3n5', chapterId: '3', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(2, 3),
      CellEntity(2, 4),
    ]),
    LevelEntity(id: 'c3n6', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(4, 4),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c3n7', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(2, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c3n8', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(2, 2),
      CellEntity(3, 3),
    ]),
    LevelEntity(id: 'c3n9', chapterId: '3', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(1, 3),
      CellEntity(1, 2),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c3n10', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(1, 4),
      CellEntity(3, 3),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c3n11', chapterId: '3', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 4),
      CellEntity(4, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c3n12', chapterId: '3', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(3, 2),
    ]),

    // ------------------- CHAPTER 4 -------------------

    LevelEntity(id: 'c4n1', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(4, 1),
      CellEntity(4, 4),
      CellEntity(1, 4),
    ]),
    LevelEntity(id: 'c4n2', chapterId: '4', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(4, 4),
      CellEntity(4, 1),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c4n3', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(4, 4),
      CellEntity(3, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c4n4', chapterId: '4', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(2, 3),
      CellEntity(3, 2),
    ]),
    LevelEntity(id: 'c4n5', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(4, 2),
      CellEntity(3, 4),
      CellEntity(1, 3),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c4n6', chapterId: '4', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c4n7', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(1, 3),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c4n8', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 3),
      CellEntity(3, 2),
      CellEntity(1, 2),
    ]),
    LevelEntity(id: 'c4n9', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(3, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c4n10', chapterId: '4', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(1, 2),
      CellEntity(3, 2),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c4n11', chapterId: '4', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(1, 3),
      CellEntity(3, 3),
      CellEntity(2, 3),
    ]),
    LevelEntity(id: 'c4n12', chapterId: '4', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(1, 2),
      CellEntity(2, 1),
      CellEntity(2, 2),
    ]),

    // ------------------- CHAPTER 5 -------------------

    LevelEntity(id: 'c5n1', chapterId: '5', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(4, 1),
      CellEntity(3, 2),
      CellEntity(2, 3),
      CellEntity(1, 4),
    ]),
    LevelEntity(id: 'c5n2', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(2, 3),
      CellEntity(4, 1),
      CellEntity(4, 4),
    ]),
    LevelEntity(id: 'c5n3', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(4, 3),
      CellEntity(4, 1),
      CellEntity(2, 3),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c5n4', chapterId: '5', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 1),
      CellEntity(3, 2),
      CellEntity(2, 3),
      CellEntity(1, 2),
    ]),
    LevelEntity(id: 'c5n5', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(3, 1),
      CellEntity(3, 3),
      CellEntity(1, 3),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c5n6', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(1, 3),
      CellEntity(3, 3),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c5n7', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(2, 3),
      CellEntity(4, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c5n8', chapterId: '5', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 1),
      CellEntity(2, 1),
      CellEntity(4, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c5n9', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(2, 1),
      CellEntity(3, 4),
      CellEntity(3, 1),
      CellEntity(2, 4),
    ]),
    LevelEntity(id: 'c5n10', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(5, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4, true),
      CellEntity(1, 5, true),
      CellEntity(2, 5, true),
      CellEntity(3, 5, true),
      CellEntity(4, 5, true),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(4, 3),
      CellEntity(2, 3),
      CellEntity(5, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c5n11', chapterId: '5', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(5, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5, true),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(4, 4),
      CellEntity(2, 4),
      CellEntity(4, 2),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c5n12', chapterId: '5', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(5, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(5, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
      CellEntity(5, 4, true),
      CellEntity(1, 5, true),
      CellEntity(2, 5, true),
      CellEntity(3, 5, true),
      CellEntity(4, 5, true),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(5, 1),
      CellEntity(2, 2),
      CellEntity(4, 2),
      CellEntity(3, 3),
    ]),

    // ------------------- CHAPTER 6 -------------------

    LevelEntity(id: 'c6n1', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 2),
      CellEntity(4, 2),
    ]),
    LevelEntity(id: 'c6n2', chapterId: '6', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(2, 3),
      CellEntity(1, 2),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c6n3', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(1, 3),
      CellEntity(1, 1),
      CellEntity(4, 3),
      CellEntity(4, 1),
    ]),
    LevelEntity(id: 'c6n4', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(4, 1),
      CellEntity(1, 4),
      CellEntity(2, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c6n5', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(3, 4),
      CellEntity(2, 3),
      CellEntity(3, 2),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c6n6', chapterId: '6', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(2, 3),
      CellEntity(1, 3),
      CellEntity(4, 2),
    ]),

    LevelEntity(id: 'c6n7', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(3, 1),
      CellEntity(3, 3),
      CellEntity(1, 3),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c6n8', chapterId: '6', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
    ], solution: [
      CellEntity(2, 1),
      CellEntity(3, 2),
      CellEntity(2, 3),
      CellEntity(1, 2),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c6n9', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
    ], solution: [
      CellEntity(2, 2),
      CellEntity(3, 3),
      CellEntity(1, 3),
      CellEntity(2, 2),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c6n10', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(2, 3),
      CellEntity(4, 4),
      CellEntity(3, 3),
      CellEntity(2, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c6n11', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(4, 1),
      CellEntity(4, 4),
      CellEntity(1, 4),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c6n12', chapterId: '6', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(5, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5, true),
      CellEntity(3, 5),
      CellEntity(4, 5, true),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(5, 5),
      CellEntity(3, 5),
      CellEntity(1, 5),
      CellEntity(5, 1),
      CellEntity(3, 1),
      CellEntity(1, 1),
    ]),

    // ------------------- CHAPTER 7 -------------------

    LevelEntity(id: 'c7n1', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(4, 1),
      CellEntity(3, 4),
      CellEntity(2, 4),
      CellEntity(3, 1),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c7n2', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(2, 3),
      CellEntity(4, 1),
      CellEntity(1, 4),
      CellEntity(4, 3),
      CellEntity(1, 2),
    ]),
    LevelEntity(id: 'c7n3', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(4, 4),
      CellEntity(1, 4),
      CellEntity(3, 1),
      CellEntity(2, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c7n4', chapterId: '7', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(4, 1),
      CellEntity(1, 4),
      CellEntity(1, 3),
      CellEntity(1, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c7n5', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(2, 3),
      CellEntity(2, 2),
      CellEntity(1, 4),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c7n6', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
    ], solution: [
      CellEntity(1, 4),
      CellEntity(2, 3),
      CellEntity(1, 3),
      CellEntity(2, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c7n7', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(2, 3),
      CellEntity(4, 1),
      CellEntity(4, 4),
      CellEntity(3, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c7n8', chapterId: '7', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(5, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5, true),
      CellEntity(2, 5),
      CellEntity(3, 5),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(3, 1),
      CellEntity(5, 3),
      CellEntity(1, 3),
      CellEntity(3, 5),
      CellEntity(3, 2),
    ]),
    LevelEntity(id: 'c7n9', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(5, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(5, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(5, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4, true),
      CellEntity(1, 5, true),
      CellEntity(2, 5, true),
      CellEntity(3, 5, true),
      CellEntity(4, 5, true),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(1, 1),
      CellEntity(2, 2),
      CellEntity(3, 3),
      CellEntity(4, 4),
      CellEntity(5, 5),
    ]),
    LevelEntity(id: 'c7n10', chapterId: '7', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(1, 3),
      CellEntity(2, 5),
      CellEntity(3, 1),
      CellEntity(5, 2),
      CellEntity(4, 4),
    ]),
    LevelEntity(id: 'c7n11', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5, true),
      CellEntity(3, 5, true),
      CellEntity(4, 5, true),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(5, 4),
      CellEntity(1, 4),
      CellEntity(5, 1),
      CellEntity(3, 2),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c7n12', chapterId: '7', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
    ], solution: [
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(1, 4),
      CellEntity(4, 4),
    ]),

    // ------------------- CHAPTER 8 -------------------

    LevelEntity(id: 'c8n1', chapterId: '8', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5),
      CellEntity(4, 5),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(1, 4),
      CellEntity(3, 5),
      CellEntity(5, 4),
      CellEntity(5, 1),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c8n2', chapterId: '8', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(5, 5),
      CellEntity(5, 1),
      CellEntity(1, 5),
      CellEntity(4, 3),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c8n3', chapterId: '8', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5, true),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(4, 4),
      CellEntity(2, 4),
      CellEntity(3, 2),
      CellEntity(5, 1),
      CellEntity(1, 1),
    ]),
    LevelEntity(id: 'c8n4', chapterId: '8', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(5, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(4, 5),
      CellEntity(2, 5),
      CellEntity(3, 2),
      CellEntity(5, 3),
      CellEntity(1, 3),
    ]),
    LevelEntity(id: 'c8n5', chapterId: '8', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2, true),
      CellEntity(5, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(1, 5),
      CellEntity(5, 5),
      CellEntity(5, 1),
      CellEntity(1, 1),
      CellEntity(3, 3),
    ]),
    LevelEntity(id: 'c8n6', chapterId: '8', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(5, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(5, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4, true),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(4, 5),
      CellEntity(2, 5),
      CellEntity(4, 1),
      CellEntity(3, 1),
      CellEntity(2, 1),
    ]),
    LevelEntity(id: 'c8n7', chapterId: '8', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(5, 1, true),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5, true),
      CellEntity(2, 5),
      CellEntity(3, 5),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(3, 5),
      CellEntity(3, 1),
      CellEntity(5, 3),
      CellEntity(1, 3),
      CellEntity(3, 3),
    ]),
    LevelEntity(id: 'c8n8', chapterId: '8', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1, true),
      CellEntity(4, 1),
      CellEntity(5, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(5, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5, true),
      CellEntity(2, 5, true),
      CellEntity(3, 5),
      CellEntity(4, 5, true),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(3, 4),
      CellEntity(5, 3),
      CellEntity(1, 3),
      CellEntity(4, 2),
      CellEntity(2, 2),
    ]),
    LevelEntity(id: 'c8n9', chapterId: '8', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(5, 2),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3, true),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
      CellEntity(5, 4, true),
      CellEntity(1, 5, true),
      CellEntity(2, 5),
      CellEntity(3, 5),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(5, 1),
      CellEntity(1, 1),
      CellEntity(3, 5),
      CellEntity(3, 1),
      CellEntity(3, 3),
    ]),
    LevelEntity(id: 'c8n10', chapterId: '8', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(5, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2, true),
      CellEntity(3, 2, true),
      CellEntity(4, 2, true),
      CellEntity(5, 2, true),
      CellEntity(1, 3),
      CellEntity(2, 3, true),
      CellEntity(3, 3),
      CellEntity(4, 3, true),
      CellEntity(5, 3),
      CellEntity(1, 4, true),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
      CellEntity(5, 4, true),
      CellEntity(1, 5, true),
      CellEntity(2, 5, true),
      CellEntity(3, 5),
      CellEntity(4, 5, true),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(3, 3),
      CellEntity(3, 4),
      CellEntity(3, 2),
      CellEntity(4, 3),
      CellEntity(2, 3),
    ]),
    LevelEntity(id: 'c8n11', chapterId: '8', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1, true),
      CellEntity(3, 1),
      CellEntity(4, 1, true),
      CellEntity(5, 1, true),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3),
      CellEntity(4, 3),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5, true),
      CellEntity(3, 5, true),
      CellEntity(4, 5, true),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(3, 2),
      CellEntity(4, 4),
      CellEntity(4, 5),
      CellEntity(2, 4),
      CellEntity(2, 5),
    ]),
    LevelEntity(id: 'c8n12', chapterId: '8', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(5, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(5, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3, true),
      CellEntity(3, 3, true),
      CellEntity(4, 3, true),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4, true),
      CellEntity(4, 4),
      CellEntity(5, 4),
      CellEntity(1, 5, true),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(4, 4),
      CellEntity(2, 4),
      CellEntity(4, 2),
      CellEntity(2, 2),
      CellEntity(5, 1),
      CellEntity(1, 1),
    ]),

    LevelEntity(id: 'c9n1', chapterId: '9', cells: [
      CellEntity(1, 1),
      CellEntity(2, 1, true),
      CellEntity(3, 1, true),
      CellEntity(4, 1, true),
      CellEntity(5, 1),
      CellEntity(1, 2, true),
      CellEntity(2, 2),
      CellEntity(3, 2, true),
      CellEntity(4, 2),
      CellEntity(5, 2, true),
      CellEntity(1, 3, true),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(5, 3, true),
      CellEntity(1, 4),
      CellEntity(2, 4, true),
      CellEntity(3, 4, true),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5, true),
      CellEntity(4, 5),
      CellEntity(5, 5),
    ], solution: [
      CellEntity(5, 5),
      CellEntity(1, 5),
      CellEntity(4, 2),
      CellEntity(5, 1),
      CellEntity(2, 2),
      CellEntity(1, 1),
    ]),

    LevelEntity(id: 'c9n12', chapterId: '9', cells: [
      CellEntity(1, 1, true),
      CellEntity(2, 1),
      CellEntity(3, 1),
      CellEntity(4, 1),
      CellEntity(5, 1),
      CellEntity(1, 2),
      CellEntity(2, 2, true),
      CellEntity(3, 2),
      CellEntity(4, 2),
      CellEntity(5, 2),
      CellEntity(1, 3),
      CellEntity(2, 3),
      CellEntity(3, 3, true),
      CellEntity(4, 3),
      CellEntity(5, 3),
      CellEntity(1, 4),
      CellEntity(2, 4),
      CellEntity(3, 4),
      CellEntity(4, 4, true),
      CellEntity(5, 4),
      CellEntity(1, 5),
      CellEntity(2, 5),
      CellEntity(3, 5),
      CellEntity(4, 5),
      CellEntity(5, 5, true),
    ], solution: [
      CellEntity(1, 2),
      CellEntity(2, 1),
      CellEntity(2, 4),
      CellEntity(4, 2),
      CellEntity(2, 5),
      CellEntity(5, 2),
      CellEntity(3, 5),
      CellEntity(5, 3),
      CellEntity(3, 4),
      CellEntity(4, 3),
    ]),
  ];
}
